### ISSUE TITLE
Add NCICCR-DLBCL Cohort

### ISSUE THREAD

**Issue by ayan-b** [ucscXena/xena-GDC-ETL#73]

**Comment by maryjgoldman** [comment]
please hold off

**Comment by maryjgoldman** [comment]
https://gdc.cancer.gov/about-data/publications/DLBCL-2018
This data was generated and analyzed alongside DLBCL data from CTSP and TCGA. Analyzed all together.

This cohort on it's own has 489 DLBCL samples. RNAseq is the only thing that is public access.

May want to visualize in a cohort with the CTSP and TCGA DLBCL samples so that can reproduce analyses from the paper? Seven bridges put them all together: https://isb-cancer-genomics-cloud.readthedocs.io/en/latest/sections/data/data2/AccessData/AccessviaIndexD.html
